on: push
name: metakar app changes
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.metakar.ir
          #          server: 195.214.235.12
          protocol: ftp
          port: 21
          username: metakar
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /metakar/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            vendor/**
            server.php
            .env
            **/.**
            public/build/**
            public/hot